- .travis.yml
- examples/pom.xml
- pom.xml
Modify example pom.xml to be self sufficient
Change-Id: Ic9e882a4ce1a8a1b96813e32d279a203744f51c9
> Increment version of compile plugin to latest.

- .travis.yml
- pom.xml
Force clean and compile avoiding tests before releasing to
get rid of trash
Change-Id: Iae32aa3b01f3153fadb43f1a087b4597d3b53a24
> Clean before release

- hbase-client/src/test/java/com/yahoo/omid/transaction/TestEndToEndScenariosWithHA.java
Change-Id: Icca04fba996617705eb07163f02b8a4d75fb2716
> Improve end2end HA test fixing some assertions and timers

- examples/run.sh
- examples/src/main/java/com/yahoo/omid/examples/BasicExample.java
- examples/src/main/java/com/yahoo/omid/examples/Configuration.java
- examples/src/main/java/com/yahoo/omid/examples/SnapshotIsolationExample.java
Improve the script to run both examples
Update instructions
Add help in Configuration class
> Add example showing Snapshot Isolation

- .travis.yml
Change-Id: I20dcfbcc43943726bfbcd6439d9724c2c474597f
> Add "force" push to git on failures

- codahale-metrics/src/main/java/com/yahoo/omid/metrics/CodahaleMetricsProvider.java
- examples/pom.xml
- examples/src/main/java/com/yahoo/omid/examples/BasicExample.java
- examples/src/main/java/com/yahoo/omid/examples/Configuration.java
- examples/src/main/java/com/yahoo/omid/examples/SnapshotIsolationExample.java
- hbase-client/src/main/java/com/yahoo/omid/transaction/HBaseTransactionManager.java
- metrics/src/main/java/com/yahoo/omid/metrics/Counter.java
- metrics/src/main/java/com/yahoo/omid/metrics/Gauge.java
- metrics/src/main/java/com/yahoo/omid/metrics/Histogram.java
- metrics/src/main/java/com/yahoo/omid/metrics/Meter.java
- transaction-client/src/main/java/com/yahoo/omid/transaction/AbstractTransactionManager.java
Change-Id: Idd3e8edbea079bd5dc8e7a61280644ad2e9a00d7
> Remove duplicate code. Move logging into util classes

- hbase-client/src/test/java/com/yahoo/omid/transaction/TestEndToEndScenariosWithHA.java
- hbase-client/src/test/resources/log4j.properties
- tso-server/src/main/java/com/yahoo/omid/tso/LeaseManager.java
Also:
- Fix log info in test
- Add ms to log4j output
Change-Id: I052a0c8ad30122bf04c9eb1c990c873433cc24c3
> Stop lease manager and wait for channel closed

- hbase-client/src/test/java/com/yahoo/omid/transaction/TestFilters.java
- hbase-client/src/test/java/com/yahoo/omid/transaction/TestShadowCells.java
- transaction-client/src/main/java/com/yahoo/omid/transaction/AbstractTransactionManager.java
Improved readability including a refactoring of some helper methods
> Improve AbstractTransactionManager

- hbase-client/src/test/java/com/yahoo/omid/transaction/TestEndToEndScenariosWithHA.java
- hbase-client/src/test/java/com/yahoo/omid/transaction/TestHBaseTransactionManager.java
- transaction-client/src/main/java/com/yahoo/omid/transaction/AbstractTransactionManager.java
- transaction-client/src/main/java/com/yahoo/omid/transaction/Transaction.java
Change-Id: I87b213726bdfbae55c1310672a82e409af86a390
> Mark readonly stransaction with a separate Transaction.Status

- transaction-client/src/main/java/com/yahoo/omid/transaction/AbstractTransactionManager.java
Change-Id: Ib6798546ae7aa708d40b837024c8a5be6cdd03d3
> Fix: Mark properly read-only transactions

- .travis.yml
Change-Id: I0c71ae71f8d2a7b601a789718fc78954f66d4784
> Give build an explicit name rather than building from a hash

- hbase-coprocessor/src/test/java/com/yahoo/omid/transaction/TestCompaction.java
In some environments, when triggering the minor compaction manually in
some tests, the compaction was promoted to a major one, so the tests
failed. Tests failing were:
- testACellDeletedNonTransactionallyIsPreservedWhenMinorCompactionOccurs()
- testTombstonesAreNotCleanedUpWhenMinorCompactionOccurs()
Change-Id: Ib5d150bc0cf38aeb2559d4c1a338569035eccb67
> Fix compaction issues in coprocessor tests

- common/src/main/java/com/yahoo/omid/YAMLUtils.java
- tso-server/conf/log4j.xml
- tso-server/pom.xml
Change-Id: I19267b6aa85068db61cdd2bae84bc99da33254f9
> Prevent TSO failure if user config is  missing

- tso-server/src/main/java/com/yahoo/omid/tso/PersistenceProcessorImpl.java
Before the checks for flush timeouts were taking always the hardcoded default timeout of 100 ms
Change-Id: Ia1d327335430a64e3a4d314c3d5db9eb1c65d7c3
> Fix batch timeout setup when flushing

- hbase-client/src/test/java/com/yahoo/omid/transaction/TestEndToEndScenariosWithHA.java
Try to reduce undesired changes in mastership due to a very low lease period
Change-Id: Ide7291c7ce3cbaad8f2e6070014d0865dd1bed47
> Increment lease time in E2E test

- common/pom.xml
Change-Id: I0886bd0079123dfb9df54700e05b660e97cfc01a
> Add generated code into build path

- examples/maven/assembly/assembly.xml
- examples/run.sh
Change-Id: Iaa84b95bc281170b423548707d611d23110be3d1
> Move config files to proper locations

- doc/site/markdown/coding-guide-and-style.md
- misc/omid_checks.xml
- pom.xml
Change-Id: I7500d5fdc5f917a0362252d8ea5ac26049bcd94c
> Add code quality reports: checkstyle and PMD

- benchmarks/src/main/java/org/apache/omid/benchmarks/utils/ScrambledZipfianGenerator.java
- hbase-client/src/main/java/org/apache/omid/transaction/ColumnWrapper.java
- hbase-client/src/main/java/org/apache/omid/transaction/HBaseTransaction.java
- hbase-coprocessor/src/main/java/org/apache/hadoop/hbase/regionserver/CompactorScanner.java
- hbase-coprocessor/src/test/java/org/apache/omid/transaction/TestCompactorScanner.java
- metrics/src/main/java/org/apache/omid/metrics/MetricsProvider.java
- statemachine/src/test/java/org/apache/statemachine/TestStateMachine.java
- transaction-client/src/main/java/org/apache/omid/transaction/CommitTimestampLocator.java
- transaction-client/src/main/java/org/apache/omid/transaction/TransactionManager.java
- transaction-client/src/main/java/org/apache/omid/tso/client/CellId.java
- transaction-client/src/main/java/org/apache/omid/tso/client/TSOFuture.java
- tso-server/src/main/java/org/apache/omid/tso/Cache.java
- tso-server/src/main/java/org/apache/omid/tso/FatalExceptionHandler.java
- tso-server/src/main/java/org/apache/omid/tso/Panicker.java
- tso-server/src/main/java/org/apache/omid/tso/ReplyProcessorImpl.java
- tso-server/src/main/java/org/apache/omid/tso/RequestProcessorImpl.java
- tso-server/src/main/java/org/apache/omid/tso/TSOStateManager.java
- tso-server/src/test/java/org/apache/omid/tso/ProgrammableTSOServer.java
- tso-server/src/test/java/org/apache/omid/tso/TestLongCache.java
- tso-server/src/test/java/org/apache/omid/tso/client/TSOClientRaw.java
Change-Id: Ia253f3edc8a00f7feb00747d498c6f38a500583c
> Clean code

- common/src/main/java/org/apache/omid/zk/ZKUtils.java
- examples/src/main/java/org/apache/omid/examples/ConfigurationExample.java
- hbase-client/src/test/java/org/apache/omid/transaction/TestEndToEndScenariosWithHA.java
- hbase-client/src/test/java/org/apache/omid/transaction/TestTxMgrFailover.java
- timestamp-storage/src/main/java/org/apache/omid/timestamp/storage/ZKModule.java
- transaction-client/src/main/java/org/apache/omid/transaction/TransactionException.java
- transaction-client/src/main/java/org/apache/omid/tso/client/TSOClient.java
Change-Id: I309f03ccc003fc42203f5581641fc0b69c46a4f9
> Use IOException in TransactionException and ZKUtils.initZKClient()

- hbase-client/src/test/java/org/apache/omid/transaction/TestAutoFlush.java
- hbase-client/src/test/java/org/apache/omid/transaction/TestCellUtils.java
- hbase-client/src/test/java/org/apache/omid/transaction/TestColumnIterator.java
- hbase-client/src/test/java/org/apache/omid/transaction/TestDeletion.java
- hbase-client/src/test/java/org/apache/omid/transaction/TestFilters.java
- hbase-client/src/test/java/org/apache/omid/transaction/TestHBaseTransactionClient.java
- hbase-client/src/test/java/org/apache/omid/transaction/TestReadPath.java
- hbase-client/src/test/java/org/apache/omid/transaction/TestSingleColumnFamily.java
- hbase-client/src/test/java/org/apache/omid/transaction/TestTransactionCleanup.java
- hbase-client/src/test/java/org/apache/omid/transaction/TestTransactionConflict.java
- hbase-client/src/test/java/org/apache/omid/transaction/TestUpdateScan.java
- hbase-commit-table/src/test/java/org/apache/omid/committable/hbase/TestHBaseCommitTable.java
- hbase-coprocessor/src/test/java/org/apache/omid/transaction/TestCompaction.java
- hbase-coprocessor/src/test/java/org/apache/omid/transaction/TestCompactorScanner.java
- timestamp-storage/src/test/java/org/apache/omid/timestamp/storage/TestHBaseTimestampStorage.java
- transaction-client/src/test/java/org/apache/omid/tso/client/TestMockTSOClient.java
- tso-server/src/test/java/org/apache/omid/tso/TestBatch.java
- tso-server/src/test/java/org/apache/omid/tso/TestLeaseManager.java
- tso-server/src/test/java/org/apache/omid/tso/TestRequestProcessor.java
- tso-server/src/test/java/org/apache/omid/tso/TestRetryProcessor.java
- tso-server/src/test/java/org/apache/omid/tso/TestTSOStateManager.java
- tso-server/src/test/java/org/apache/omid/tso/client/TestIntegrationOfTSOClientServerBasicFunctionality.java
No changes in functionality have been done
Change-Id: I48a5409dacac0716191ce332f2d0bbe995ed5761
> Remove JUnit asserts

- benchmarks/src/main/java/org/apache/omid/benchmarks/tso/RawTxRunner.java
- hbase-client/src/test/java/org/apache/omid/transaction/TestBaillisAnomaliesWithTXs.java
> analyze the transactional anomalies described by P. Baillis et al.

- examples/pom.xml
- examples/run.sh
- examples/src/main/java/org/apache/omid/examples/ParallelExecution.java
- examples/src/main/java/org/apache/omid/examples/RowIdGenerator.java
- examples/src/main/java/org/apache/omid/examples/SnapshotIsolationExample.java
- pom.xml
Change-Id: I866396d97943e4c78e5a708b710776219e55d6cc
> Parallel execution example

- benchmarks/bin/benchmarks.sh
- benchmarks/bin/omid-env.sh
- benchmarks/src/main/java/org/apache/omid/benchmarks/tso/TSOServerBenchmarkConfig.java
- benchmarks/src/main/resources/default-tso-server-benchmark-config.yml
Change-Id: Ifdd68c6ed75e7be9d758425468c3ee099b102127
> Fix benchmark configs to let them run on secure Hbase

- tso-server/src/test/java/org/apache/omid/tso/TestReplyProcessor.java
Change-Id: I7105b1698ee4d1095baabdf844928518da57a4a7
> Add test battery for batch re-ordering functionality in reply processor

- .travis.yml
HBase profile was missing in the maven commands after
we resolved [OMID-30]
Change-Id: I9c4570b185fe63a17ff273e352dbc1a2f6f679dd
> [OMID-34] Fix Travis builds

- benchmarks/bin/benchmarks.sh
- benchmarks/bin/omid-env.sh
- doc/site/resources/css/site.css
- examples/run.sh
- pom.xml
- tso-server/bin/omid.sh
- tso-server/conf/omid-env.sh
Change-Id: I09c99ccadb479b211882a1e09735da0fd4fc65a3
> [OMID-31] Add missing license header

- tso-server/src/main/java/org/apache/omid/tso/Batch.java
- tso-server/src/main/java/org/apache/omid/tso/MonitoringContext.java
- tso-server/src/main/java/org/apache/omid/tso/PersistenceProcessorHandler.java
- tso-server/src/main/java/org/apache/omid/tso/ReplyProcessorImpl.java
- tso-server/src/main/java/org/apache/omid/tso/RequestProcessorImpl.java
- tso-server/src/main/java/org/apache/omid/tso/RetryProcessorImpl.java
- tso-server/src/test/java/org/apache/omid/tso/TestBatch.java
- tso-server/src/test/java/org/apache/omid/tso/TestReplyProcessor.java
After refactoring the TSO pipeline, metrics -specially those related to
latencies- were not representative anymore. Also, new specialized metrics
have been added to measure special events.
Change-Id: Ie607872d0b2f3cf9e782eff70119e9d834979e43
> [OMID-35] Fix and improve TSO metrics

- tso-server/src/main/java/org/apache/omid/tso/PersistenceProcessorImpl.java
- tso-server/src/main/java/org/apache/omid/tso/ReplyProcessorImpl.java
- tso-server/src/main/java/org/apache/omid/tso/RequestProcessorImpl.java
- tso-server/src/main/java/org/apache/omid/tso/RetryProcessorImpl.java
Use the disruptor API to create disruptor components in Omid processors instead of using the internal wiring. 
Clarifies the instantiation of the disruptor components in all the processors.
Change-Id: I5d164bead9de6536495f08578cf6a02171b5d69f
> [OMID-37] Improve creation of Disruptor components

- hbase-coprocessor/pom.xml
- hbase-coprocessor/src/main/java/org/apache/hadoop/hbase/regionserver/CompactorScanner.java
- hbase-coprocessor/src/main/java/org/apache/omid/hbase/coprocessor/metrics/CompactorCoprocessorMetrics.java
- hbase-coprocessor/src/main/java/org/apache/omid/hbase/coprocessor/metrics/CompactorCoprocessorMetricsSource.java
- hbase-coprocessor/src/main/java/org/apache/omid/transaction/OmidCompactor.java
- hbase-coprocessor/src/test/java/org/apache/omid/hbase/coprocessor/metrics/TestCompactorCoprocessorMetrics.java
- hbase-coprocessor/src/test/java/org/apache/omid/transaction/TestCompactorScanner.java
Histograms added:
-time on compactions
-time on processing a cell
-time on contacting commit table for retrieve a commit TS (RPC)
Counters added:
-major & minor compactions
-scanned rows (in all compactions)
-total cells explored (in all compactions)
-retained cells (in all compactions)
-shadow cells healed (in all compactions)
-discarded cells (in all compactions)
-tombstone cells found (in all compactions)
Change-Id: I4a3607f1992505896e674ddb073a51ebf2582550
> [OMID-39] Implement coprocessor metrics in Hadoop

- DISCLAIMER
Required in incubator projects
Change-Id: I079cf7fc21cb9794417a0f046f7c88f9058719a4
> Add DISCLAIMER file

- NOTICE
Change-Id: Iecd6d9cf30d3b0cbbe72603f844f9204266a77b5
> [OMID-44] Add reference to Yahoo code in NOTICE file
